package com.github.chen0040.leetcode.day08.easy;


import java.util.HashMap;
import java.util.Map;


/**
 * Created by xschen on 5/8/2017.
 *
 * summary:
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 *
 * link: https://leetcode.com/problems/find-the-difference/description/
 */
public class FindTheDifference {
   public class Solution {
      public char findTheDifference(String s, String t) {
         Map<Character, Integer> chars = new HashMap<Character, Integer>();
         for(int i=0; i < t.length(); ++i) {
            char c = t.charAt(i);
            chars.put(c, chars.getOrDefault(c, 0) + 1);
         }
         for(int i=0; i < s.length(); ++i) {
            char c = s.charAt(i);
            if(chars.containsKey(c)) {
               int count = chars.get(c);
               if(count > 1){
                  chars.put(c, count - 1);
               } else {
                  chars.remove(c);
               }
            }
         }
         char added = '0';
         for(Character c : chars.keySet()) {
            added = c;
            break;
         }
         return added;
      }
   }
}
